// Employees + payroll smoke test against a RUNNING API on a FRESH database (it creates employees).
//   npm run dev   ->   npm run smoke:staff      (API_BASE overrides http://localhost:3000/api)
const B=process.env.API_BASE||'http://localhost:3000/api';
let pass=0,fail=0;const fails=[];
const ok=(c,m)=>{ if(c){pass++;console.log('  ok  ',m)}else{fail++;fails.push(m);console.log('  FAIL',m)} };
const call=async(m,p,t,b)=>{const r=await fetch(B+p,{method:m,headers:{'Content-Type':'application/json',...(t?{Authorization:'Bearer '+t}:{})},body:b?JSON.stringify(b):undefined});return {s:r.status,j:await r.json().catch(()=>null)}};
const get=async(p,t)=>(await call('GET',p,t)).j?.data;
const msg=r=>r.j?.message||'';
const login=async(i,p)=>(await fetch(B+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({identifier:i,password:p})}).then(r=>r.json())).data;
const L=await login('superadmin','Admin@123'); const A=L.accessToken; const BR=L.user.branchId;
const MONTH=new Date().toISOString().slice(0,7);

console.log('# hire an employee in one step');
let r=await call('POST','/employees',A,{firstName:'Rabia',lastName:'Khan',role:'teacher',email:'rabia@school.test',phone:'0300 5551111',gender:'female',department:'Science',designation:'Senior Teacher',hireDate:'2025-04-01',basicSalary:60000});
ok(r.s===201,'teacher hired '+r.s+' '+msg(r)); const rabia=r.j?.data; 
ok(/^EMP-\d{4}$/.test(rabia?.employee?.staffNo),'readable staff number '+rabia?.employee?.staffNo);
ok(rabia?.credentials?.[0]?.username&&rabia?.credentials?.[0]?.password,'login details returned once');
const rl=await login(rabia.credentials[0].username,rabia.credentials[0].password); ok(!!rl?.accessToken,'new employee can log in');
const tList=await get('/teachers?limit=50',A); const rt=tList.find(t=>t.email==='rabia@school.test'); ok(rt&&rt.staffNo===rabia.employee.staffNo,'Teacher row shares the SAME staff number as the Staff row ('+rt?.staffNo+')');
const sList=await get('/staff?limit=50',A); const rs=sList.find(s=>s.email==='rabia@school.test'); ok(rs&&rs.department==='Science'&&rs.designation==='Senior Teacher'&&Number(rs.basicSalary)===60000&&rs.employeeType==='teacher'&&rs.username===rabia.credentials[0].username,'staff row has department, designation, salary, type, username');
r=await call('POST','/employees',A,{firstName:'Dup',role:'teacher',email:'rabia@school.test'}); ok(r.s===409,'same email rejected: '+msg(r));
r=await call('POST','/employees',A,{firstName:'Bad',role:'parent',email:'bad@school.test'}); ok(r.s===400,'non-employee role rejected: '+msg(r));
r=await call('POST','/employees',A,{firstName:'Bad',role:'staff',email:'nomail'}); ok(r.s===400,'bad email rejected');
r=await call('POST','/employees',A,{firstName:'Neg',role:'staff',email:'neg@school.test',basicSalary:-5}); ok(r.s===400,'negative salary rejected');
const par=await Promise.all([1,2,3,4].map(i=>call('POST','/employees',A,{firstName:'Par'+i,lastName:'Race',role:'accountant',email:`par${i}@school.test`,basicSalary:40000+i})));
const nos=par.map(p=>p.j?.data?.employee?.staffNo); ok(par.every(p=>p.s===201)&&new Set(nos).size===4,'4 parallel hires -> 4 distinct staff numbers '+nos.join(','));
const acc=par[0].j.data; const accLogin=await login(acc.credentials[0].username,acc.credentials[0].password);

console.log('# user created the old way also gets a proper profile');
r=await call('POST','/users',A,{username:'warden9',email:'warden9@school.test',firstName:'Imtiaz',lastName:'Ali',role:'hostel_warden',gender:'male',branchId:BR,password:'Passw0rd!x'}); ok(r.s===201,'user created');
const wS=(await get('/staff?limit=100',A)).find(s=>s.email==='warden9@school.test'); ok(wS&&wS.employeeType==='hostel_warden'&&wS.gender==='male'&&wS.hireDate&&wS.designation==='Hostel Warden'&&/^EMP-/.test(wS.staffNo),'profile has type, gender, hire date, designation, EMP number');

console.log('# profile stays in step with the login');
r=await call('PUT','/users/'+(await get('/users?q=warden9',A))[0].id,A,{role:'librarian'}); ok(r.s===200,'role changed to librarian');
let w2=(await get('/staff?limit=100',A)).find(s=>s.email==='warden9@school.test'); ok(w2.employeeType==='librarian','employee type follows the role change ('+w2.employeeType+')');
const wuid=(await get('/users?q=warden9',A))[0].id;
r=await call('PUT','/users/'+wuid,A,{role:'parent'}); w2=(await get('/staff?limit=100',A)).find(s=>s.email==='warden9@school.test'); ok(w2.isActive===false,'moved to a non-employee role -> staff profile deactivated');
await call('PUT','/users/'+wuid,A,{role:'receptionist'}); w2=(await get('/staff?limit=100',A)).find(s=>s.email==='warden9@school.test'); ok(w2.isActive===true&&w2.employeeType==='receptionist','back to an employee role -> reactivated as receptionist');
r=await call('PATCH','/users/'+wuid+'/status',A,{isActive:false}); w2=(await get('/staff?limit=100',A)).find(s=>s.email==='warden9@school.test'); ok(w2.isActive===false,'deactivating the login deactivates the profile');
await call('PATCH','/users/'+wuid+'/status',A,{isActive:true});
r=await call('PUT','/users/'+wuid,A,{firstName:'Imtiaz Ahmed'}); w2=(await get('/staff?limit=100',A)).find(s=>s.email==='warden9@school.test'); ok(w2.firstName==='Imtiaz Ahmed','renaming the login renames the profile');
r=await call('PUT','/staff/'+rs.id,A,{firstName:'Rabia',lastName:'Khan-Malik',phone:'0300 7778888',department:'Physics'}); ok(r.s===200,'edit staff profile '+r.s+' '+msg(r));
const ru=(await get('/users?q=rabia',A))[0]; ok(ru.lastName==='Khan-Malik'&&ru.phone==='0300 7778888','profile edit is mirrored to the login');
const rt2=(await get('/teachers?limit=50',A)).find(t=>t.email==='rabia@school.test'); ok(rt2.lastName==='Khan-Malik','...and to the Teacher record');
r=await call('PUT','/staff/'+rs.id,A,{employeeType:'principal',isActive:false}); const rs2=(await get('/staff?limit=50',A)).find(s=>s.email==='rabia@school.test'); ok(rs2.employeeType==='teacher'&&rs2.isActive===true,'employee type and active cannot be typed over (they follow the login)');
r=await call('PUT','/staff/'+rs.id,A,{email:'imtiaz'}); ok(r.s===400,'bad email on profile rejected');
r=await call('PUT','/staff/'+rs.id,A,{email:par[0].j.data.employee.email||'par1@school.test'}); ok(r.s===409,'email of another login rejected: '+msg(r));
r=await call('PUT','/staff/'+rs.id,A,{basicSalary:-1}); ok(r.s===400,'negative salary on profile rejected');
r=await call('PUT','/staff/'+rs.id,A,{staffNo:par[0].j.data.employee.staffNo}); ok(r.s===409,'duplicate staff number rejected');
r=await call('DELETE','/staff/'+rs.id,A); ok(r.s===400,'cannot delete an employee who has an active login: '+msg(r));
const accRow=(await get('/staff?limit=100',A)).find(s=>s.email==='par2@school.test'); r=await call('POST','/teachers',A,{userId:accRow.userId,staffNo:'T-9',firstName:'X'}); ok(r.s===400,'teacher profile for a non-teacher login rejected: '+msg(r));

console.log('# payroll');
const sum0=await call('GET','/payroll/summary?month='+MONTH,A); ok(sum0.s===200&&sum0.j.data.notYetOnPayroll>=5,'summary: employees not yet on payroll ('+sum0.j?.data?.notYetOnPayroll+')');
const g1=await call('POST','/payroll/generate',A,{month:MONTH}); ok(g1.s===201&&g1.j.data.created>=5,'generate: '+msg(g1)); const created1=g1.j?.data?.created;
ok(g1.j.data.skippedNoSalary>=1,'people without a salary are skipped ('+g1.j.data.skippedNoSalary+')');
const g2=await call('POST','/payroll/generate',A,{month:MONTH}); ok(g2.j.data.created===0&&g2.j.data.skippedExisting===created1,'running again creates nothing');
const items=(await get('/payroll?limit=100&filter[month]='+MONTH,A)); ok(items.every(i=>i.payeeName)&&items.every(i=>i.status==='draft'),'payroll list shows names; all drafts');
const rabiaItem=items.find(i=>i.payeeName.startsWith('Rabia')); ok(rabiaItem&&Number(rabiaItem.netPay)===60000,'Rabia (teacher) paid via her Staff row at 60000');
const dupT=await call('POST','/payroll',A,{month:MONTH,payeeType:'teacher',teacherId:rt.id,basicSalary:1000}); ok(dupT.s===409,'a teacher cannot be paid twice via her Teacher record: '+msg(dupT));
const dupS=await call('POST','/payroll',A,{month:MONTH,payeeType:'staff',staffId:rs.id,basicSalary:1000}); ok(dupS.s===409,'nor twice via Staff');
const wrongStatus=await call('POST','/payroll',A,{month:'2026-01',payeeType:'staff',staffId:rs.id,basicSalary:1000,status:'paid',paidOn:'2026-01-31'}); ok(wrongStatus.s===400,'new items cannot start as paid');
const negNet=await call('PUT','/payroll/'+rabiaItem.id,A,{deductions:70000}); ok(negNet.s===400,'deductions above salary rejected: '+msg(negNet));
const edit=await call('PUT','/payroll/'+rabiaItem.id,A,{allowances:5000,deductions:1000}); ok(edit.s===200&&Number(edit.j.data.netPay)===64000,'draft amounts editable, net recalculated = 64000');
const earlyPaid=await call('PUT','/payroll/'+rabiaItem.id,A,{status:'paid'}); ok(earlyPaid.s===400,'draft cannot jump to paid: '+msg(earlyPaid));
const pslEarly=await call('POST','/payslips',A,{payrollItemId:rabiaItem.id}); ok(pslEarly.s===400,'no payslip for a draft: '+msg(pslEarly));
const noBulk=await call('POST','/payroll/bulk-status',A,{month:MONTH,from:'draft',to:'paid'}); ok(noBulk.s===400,'bulk draft->paid refused');
const ap=await call('POST','/payroll/bulk-status',A,{month:MONTH,from:'draft',to:'approved'}); ok(ap.s===200&&ap.j.data.updated===created1,'approve all drafts ('+ap.j?.data?.updated+')');
const lockAmt=await call('PUT','/payroll/'+rabiaItem.id,A,{basicSalary:99999}); ok(lockAmt.s===400,'approved: amounts locked: '+msg(lockAmt));
const delAp=await call('DELETE','/payroll/'+rabiaItem.id,A); ok(delAp.s===400,'approved item cannot be deleted');
const ps=await call('POST','/payroll/payslips',A,{month:MONTH}); ok(ps.s===201&&ps.j.data.created===created1,'payslips created for all approved items');
const ps2=await call('POST','/payroll/payslips',A,{month:MONTH}); ok(ps2.j.data.created===0,'payslips not duplicated');
const slips=await get('/payslips?limit=100',A); ok(slips.length===created1&&new Set(slips.map(s=>s.payslipNo)).size===created1&&slips.every(s=>/^PS-\d{6}-\d{4}$/.test(s.payslipNo)),'unique readable payslip numbers e.g. '+slips[0]?.payslipNo);
const paidFuture=await call('POST','/payroll/bulk-status',A,{month:MONTH,from:'approved',to:'paid',paidOn:'2999-01-01'}); ok(paidFuture.s===400,'future paid-on rejected');
const pay=await call('POST','/payroll/bulk-status',A,{month:MONTH,from:'approved',to:'paid'}); ok(pay.s===200&&pay.j.data.updated===created1,'mark all paid');
const paidEdit=await call('PUT','/payroll/'+rabiaItem.id,A,{allowances:1}); ok(paidEdit.s===400&&/locked/i.test(msg(paidEdit)),'paid salary is locked: '+msg(paidEdit));
const paidBack=await call('PUT','/payroll/'+rabiaItem.id,A,{status:'draft'}); ok(paidBack.s===400,'paid cannot go back to draft');
const sum1=await call('GET','/payroll/summary?month='+MONTH,A); ok(sum1.j.data.paid===created1&&sum1.j.data.totalPaid>0&&sum1.j.data.notYetOnPayroll===0,'summary after payment '+JSON.stringify(sum1.j.data));
const far=await call('POST','/payroll/generate',A,{month:'2099-01'}); ok(far.s===400,'cannot prepare payroll far in the future');
const badM=await call('POST','/payroll/generate',A,{month:'2026-13'}); ok(badM.s===400,'bad month rejected');
const forbid=await call('POST','/payroll/generate',accLogin.accessToken,{month:'2026-01'}); ok(forbid.s===201||forbid.s===200,'accountant can run payroll ('+forbid.s+')');
const tl=await login(rabia.credentials[0].username,rabia.credentials[0].password); const tDeny=await call('POST','/payroll/generate',tl.accessToken,{month:MONTH}); ok(tDeny.s===403,'a teacher cannot run payroll '+tDeny.s);
const tSee=await call('GET','/payroll?limit=5',tl.accessToken); ok(tSee.s===403,'a teacher cannot read everyone\'s payroll '+tSee.s);

console.log('# deactivated employees leave payroll');
const nextM=(()=>{const d=new Date();d.setUTCMonth(d.getUTCMonth()+1);return d.toISOString().slice(0,7)})();
await call('PATCH','/users/'+acc.employee.userId+'/status',A,{isActive:false});
const g3=await call('POST','/payroll/generate',A,{month:nextM}); const names=(g3.j.data.people||[]).map(p=>p.name); ok(g3.s===201&&!names.includes('Par1 Race'),'inactive employee is not on next month\'s payroll ('+g3.j.data.created+' prepared)');
console.log(`\n${pass} passed, ${fail} failed`); if(fail) console.log('FAILED:\n - '+fails.join('\n - '));
