export interface PermissionMap {
  [role: string]: string[];
}

/**
 * Permission matrix used by the `authorize` middleware.
 * A permission is `module:action` (e.g. `students:create`).
 * `*` grants all. Roles:
 * super_admin, admin, principal, teacher, parent, student,
 * accountant, librarian, transport_manager, hostel_warden, receptionist
 */
export const ROLE_PERMISSIONS: PermissionMap = {
  super_admin: ["*"],
  admin: [
    "*",
    "users:read",
    "users:create",
    "users:update",
    "users:delete",
    "settings:manage",
    "audit-logs:read",
    "reports:read",
    "reports:export",
  ],
  principal: [
    "dashboard:read",
    "students:read",
    "students:create",
    "students:update",
    "teachers:read",
    "teachers:create",
    "teachers:update",
    "staff:read",
    "classes:read",
    "sections:read",
    "attendance:read",
    "exams:read",
    "exams:create",
    "exam-results:read",
    "exam-results:update",
    "timetable:read",
    "reports:read",
    "reports:export",
    "notices:create",
    "announcements:create",
    "messages:send",
    "complaints:read",
    "complaints:update",
    "audit-logs:read",
  ],
  teacher: [
    "dashboard:read",
    "students:read",
    "classes:read",
    "sections:read",
    "attendance:read",
    "attendance:create",
    "attendance:update",
    "assignments:create",
    "assignments:update",
    "submissions:read",
    "submissions:update",
    "exams:create",
    "exam-results:create",
    "gradebook:read",
    "gradebook:update",
    "lesson-plans:create",
    "syllabus:read",
    "timetable:read",
    "messages:send",
    "notices:read",
  ],
  parent: [
    "dashboard:read",
    "students:read",
    "attendance:read",
    "exam-results:read",
    "report-cards:read",
    "fees:read",
    "invoices:read",
    "payments:create",
    "homework:read",
    "notices:read",
    "announcements:read",
    "messages:send",
    "messages:read",
    "leaves:create",
    "complaints:create",
    "timetable:read",
    "events:read",
  ],
  student: [
    "dashboard:read",
    "attendance:read",
    "exam-results:read",
    "report-cards:read",
    "homework:read",
    "submissions:create",
    "notices:read",
    "announcements:read",
    "messages:send",
    "messages:read",
    "timetable:read",
    "events:read",
    "library:read",
    "book-issues:create",
  ],
  accountant: [
    "dashboard:read",
    "fees:read",
    "fees:create",
    "invoices:read",
    "invoices:create",
    "invoices:update",
    "payments:read",
    "payments:create",
    "receipts:read",
    "receipts:create",
    "refunds:create",
    "expenses:read",
    "expenses:create",
    "payroll:read",
    "payroll:create",
    "reports:read",
    "reports:export",
    "students:read",
  ],
  librarian: [
    "dashboard:read",
    "library:read",
    "library:create",
    "book-issues:read",
    "book-issues:create",
    "book-issues:update",
    "book-fines:read",
    "book-fines:create",
    "students:read",
    "notices:read",
  ],
  transport_manager: [
    "dashboard:read",
    "routes:read",
    "routes:create",
    "routes:update",
    "vehicles:read",
    "vehicles:create",
    "vehicles:update",
    "route-stops:read",
    "route-stops:create",
    "driver-assignments:read",
    "driver-assignments:create",
    "student-transport:read",
    "student-transport:create",
    "students:read",
    "notices:read",
  ],
  hostel_warden: [
    "dashboard:read",
    "hostels:read",
    "hostels:update",
    "rooms:read",
    "rooms:create",
    "beds:read",
    "beds:update",
    "hostel-allocations:read",
    "hostel-allocations:create",
    "hostel-allocations:update",
    "students:read",
    "notices:read",
    "attendance:read",
  ],
  receptionist: [
    "dashboard:read",
    "admissions:read",
    "admissions:create",
    "admissions:update",
    "students:read",
    "students:create",
    "visitors:create",
    "complaints:create",
    "notices:read",
  ],
};

export function permissionsForRole(role: string): string[] {
  return ROLE_PERMISSIONS[role] || [];
}

export function hasPermission(role: string, permission: string): boolean {
  const perms = permissionsForRole(role);
  if (perms.includes("*")) return true;
  return perms.includes(permission);
}